Design for quote
Perfectro/symbaroum-foundry-vtt pull request #6
Opened 2020-10-25 22:53 UTC by Qaw

2020-10-26 06:41 UTC, Perfectro requested changes

2020-10-26 06:41 UTC, Perfectro commented on lang/en.json
> +  "BIO.UNSPENTEXPERIENCE": "Unspent",
Should be `BIO.UNSPENT_EXPERIENCE`

2020-10-26 06:41 UTC, Perfectro commented on lang/fr.json
> +  "TAB.GEAR": "ÉQUIPEMENT",
Should stay in plural, like `NOTES`

2020-10-26 06:41 UTC, Perfectro commented on style/common/actor.css
> +    border: 5px solid transparent;
By doing this, margin isn't the same everywhere since the `border-image` need 10px.
And I prefer to stay with a margin of 10px.
![image](https://user-images.githubusercontent.com/5683489/97140031-1b74c680-175c-11eb-837b-1a9640657253.png)

2020-10-26 06:41 UTC, Perfectro commented on style/sheet/player.css
> +.symbaroum.sheet.actor .player .sheet-header .unspentexperience {
Should be `unspent-experience`.

2020-10-26 06:41 UTC, Perfectro commented on style/sheet/player.css
> +    padding: 3px;
Don't reduce the padding of the tabs just so it will fit in the sheet.
You can reduce the size of the scrolling element if you need to.

2020-10-26 06:41 UTC, Perfectro commented on template/sheet/player.html
> +                        <label>{{localize "BIO.UNSPENTEXPERIENCE"}}</label>
It should stay in the same line as before.
![image](https://user-images.githubusercontent.com/5683489/97140712-84107300-175d-11eb-8336-1bde3b5379ce.png)
Splitting it means it is two different thing.
![image](https://user-images.githubusercontent.com/5683489/97140749-9be7f700-175d-11eb-8852-12f4bd864ce4.png)

2020-10-26 06:41 UTC, Perfectro commented on template/sheet/player.html
> +                    <div class="quote">
The avatar should at least be center.
![image](https://user-images.githubusercontent.com/5683489/97140840-c89c0e80-175d-11eb-9739-59e465ae4d6e.png)
But even then, adding a fourth row feel like the sheet lost a bit of aesthetic.
And the label `Quote` is bigger than the other label. It trigger me 😄

2020-10-26 10:48 UTC, Qaw commented on lang/fr.json
> +  "TAB.GEAR": "ÉQUIPEMENT",
In French, you can write several notes but you don't speak about Equipements.

2020-10-26 10:49 UTC, Qaw commented on style/sheet/player.css
> +    padding: 3px;
I reduce padding and border to avoid the vertical scrolling bar ... How can I do it ?

2020-10-26 10:51 UTC, Qaw commented on template/sheet/player.html
> +                        <label>{{localize "BIO.UNSPENTEXPERIENCE"}}</label>
In the real player sheet, you have 2 fields with two labels, but it doesn't fit here.

2020-10-26 11:02 UTC, Qaw commented on template/sheet/player.html
> +                    <div class="quote">
But the quote could be a sentence, elsewhere it's limited to a few words (27 characters).
At least perhaps to have a sheet with more place.
In the same way : in the Gear Tab, on the Gear part, if the name is more than 17 characters ... the sheet explodes.

2020-10-27 02:11 UTC, Perfectro commented on style/sheet/player.css
> +    padding: 3px;
You can reduce the height of scrolling element like `abilities-powers` div on the main tab for example.
File `player-main.css` L200
`height: 350px;`

2020-10-27 02:18 UTC, Perfectro commented on template/sheet/player.html
> +                        <label>{{localize "BIO.UNSPENTEXPERIENCE"}}</label>
You can use `title` on an input like this : `<input title="Current Experience"/>`

2020-10-27 02:22 UTC, Perfectro commented on template/sheet/player.html
> +                    <div class="quote">
I mean the `<label>` markup. Not the `<input>`.

2020-11-02 21:17 UTC, Qaw commented
It's seems it's too different of what you want, I close the PR.

2020-11-02 21:17 UTC, closed without merging